### This notebook is used to calculate the simplified duct bank model based on matrix formulation.

#### First we show an example of 3x2 duct bank and define several key parameters of the duct bank.

![Example Box 3x2](box3x2.png "Example Box 3x2")

Here are the key parameters related to the duct bank, including their diameters and layout in the concrete. 

(todo - draw an illustrative figure)

First we have the diameters and thickness of the duct bank.

- $id_{duct}$: Inside diameter of the duct or conduit.

- $t_{duct}$: Thickness of the duct.

- $od_{duct}$: Outside diameter of the duct, calculated by adding two times $t_{duct}$ to $id_{duct}$.




Second, we have the layout of the duct bank in the concrete.

- $row$: The number of rows of duct banks in the layout.

- $col$: The number of columns of duct banks in the layout.

- $x$: The shorter side of the rectangular duct bank, measured in inches.

- $y$: The longer side of the rectangular duct bank, measured in inches.

- $L_{top}$: The depth of the concrete top surface below the earth's surface, measured in inches.

- $d_{vert}$: The vertical distance between the centers of two duct banks.

- $d_{hori}$: The horizontal distance between the centers of two duct banks.

- $d_{top}$: The distance between the center of the __first__ row duct bank and the concrete __top__ surface.

- $d_{down}$: The distance between the center of the __last__ row duct bank and the concrete __button__ surface.

- $d_{left}$: The distance between the center of the __first__ column duct bank and the concrete __left__ surface.

- $d_{right}$: The distance between the center of the __last__ row duct bank and the concrete __right__ surface.

#### Now we show the matrix formulation for 2 by 2 duct bank. 

Suppose we have a 2x2 duct bank system. There are four ducts indexed as $1, 2, 3, 4$. 

- $T_i, \; i=$ 1, 2, 3, 4 is the cable core temperature for cable $i$
- $Q_i$ is the heat source input from cable $i$ in watt

The four ducts are confined in a concrete and buried underground. The heat come from the four cables and finally the concrete reaches a heat equilibrium by dissipating heat to the ambient air via the earth fill on top. We have

- $T_d$ is the duct bank surface temperature in degree Celsius
- $T_a$ is the ambient air temperature in degree Celsius.


Now, we define 

- $R_{ii}$: the thermal resistance between the cable and the duct bank surface for cable $i$ (inside duct bank $i)

- $R_{ij}$: the thermal resistance between cable $i$ and cable $j$

Then we can write the following 5 thermal equilibrium equations:

\begin{equation}
\begin{aligned}
T_d - T_a &= (Q_1 + Q_2 + Q_3 + Q_4) \times R_g \\
T_1 - T_d &= Q_1 R_{11} + Q_2 R_{12} + Q_3 R_{13} + Q_4 R_{14} \\
T_2 - T_d &= Q_1 R_{21} + Q_2 R_{22} + Q_3 R_{23} + Q_4 R_{24} \\
T_3 - T_d &= Q_1 R_{31} + Q_2 R_{32} + Q_3 R_{33} + Q_4 R_{34} \\
T_4 - T_d &= Q_1 R_{41} + Q_2 R_{42} + Q_3 R_{43} + Q_4 R_{44}
\end{aligned}
\end{equation}



Defining

\begin{equation}
\boldsymbol{x} = 
\begin{bmatrix}
T_1 \\
T_2 \\
T_3 \\
T_4 \\
T_d \\
\end{bmatrix}
, \quad
\boldsymbol{u} = 
\begin{bmatrix}
Q_1 \\
Q_2 \\
Q_3 \\
Q_4 \\
T_a \\
\end{bmatrix}
,
\end{equation}

then we have the state-spacee equation as follows:

$$
\boldsymbol{\dot x} = \boldsymbol{A} \boldsymbol{x} + \boldsymbol{B} \boldsymbol{u}
$$

where 

\begin{equation}
\boldsymbol{A} = 
\begin{bmatrix}
0& 0& 0& 0& -1\\
-1& 0& 0& 0& 1\\
0& -1& 0& 0& 1\\
0& 0& -1& 0& 1\\
0& 0& 0& -1& 1\\
\end{bmatrix}
, \quad
\boldsymbol{B} = 
\begin{bmatrix}
R_g& R_g& R_g& R_g& 1\\
R_{11}& R_{12}& R_{13}& R_{14}& 0\\
R_{21}& R_{22}& R_{23}& R_{24}& 0\\
R_{31}& R_{32}& R_{33}& R_{34}& 0\\
R_{41}& R_{42}& R_{43}& R_{44}& 0\\
\end{bmatrix}
\end{equation}

When the duct banks, concrete, and earth reach a heat equilibrium, we have $\boldsymbol{\dot x} = 0$.

Suppose the thermal resistance between 

In the following figure, the matrix A and B are given

\begin{equation}
\boldsymbol{A} = 
\begin{bmatrix}
0& 0& 0& 0& -1\\
-1& 0& 0& 0& 1\\
0& -1& 0& 0& 1\\
0& 0& -1& 0& 1\\
0& 0& 0& -1& 1\\
\end{bmatrix}
, \quad
\boldsymbol{B} = 
\begin{bmatrix}
R_g& R_g& R_g& R_g& 1\\
R_1& R_{12}& R_{13}& R_{14}& 0\\
R_{21}& R_2& R_{23}& R_{24}& 0\\
R_{31}& R_{32}& R_3& R_{34}& 0\\
R_{41}& R_{42}& R_{43}& R_4& 0\\
\end{bmatrix}
\end{equation}

Therefore, we have 

$$\boldsymbol{A} \boldsymbol{x} + \boldsymbol{B} \boldsymbol{u} = 0,$$

which enables us to get 

$$\boldsymbol{x} = - \boldsymbol{A}^{-1} \boldsymbol{B} \boldsymbol{u} $$


<!-- ![Duct bank example 2 by 2](2by2example.jpg) -->

#### The matrix formulation for N duct bank (m by n)

\begin{equation}
\begin{aligned}
T_d - T_a &= \sum_{i=1}^N Q_i \times R_g \\
T_1 - T_d &= \sum_{i=1}^N Q_i \times R_{1i} \\
T_2 - T_d &= \sum_{i=1}^N Q_i \times R_{2i} \\
&\vdots \\
T_N - T_d &= \sum_{i=1}^N Q_i \times R_{Ni}
\end{aligned}
\end{equation}


Similarly, we can define

\begin{equation}
\boldsymbol{x} =
\begin{bmatrix}
T_1 \\
T_2 \\
\vdots \\
T_N \\
T_d \\
\end{bmatrix}
, \quad
\boldsymbol{u} =
\begin{bmatrix}
Q_1 \\
Q_2 \\
\vdots \\
Q_N \\
T_a \\
\end{bmatrix}
,
\end{equation}


then we have the state-spacee equation as follows:
$$
\boldsymbol{\dot x} = \boldsymbol{A} \boldsymbol{x} + \boldsymbol{B} \boldsymbol{u}
$$

where 

\begin{equation}
\boldsymbol{A} =
\begin{bmatrix}
0& 0& \cdots & 0& -1\\
-1& 0& \cdots & 0& 1\\
0& -1& \cdots & 0& 1\\
\vdots& \vdots& \ddots & \vdots& \vdots\\
0& 0& \cdots & -1& 1\\
\end{bmatrix}
, \quad
\boldsymbol{B} =
\begin{bmatrix}
R_g& R_g& \cdots & R_g& 1\\
R_{11}& R_{12}& \cdots & R_{1N}& 0 \\
R_{21}& R_{22}& \cdots & R_{2N}& 0 \\
\vdots& \vdots& \ddots & \vdots& \vdots\\
R_{N1}& R_{N2}& \cdots & R_{NN}& 0\\
\end{bmatrix}
\end{equation}

Similarly, we can obtain 

$$\boldsymbol{x} = - \boldsymbol{A}^{-1} \boldsymbol{B} \boldsymbol{u} $$

when it reaches an thermal equilibrium $\boldsymbol{\dot x} = 0$.

#### Now we show the specific calculation of the $R_{ij}$

Let us first review the parameters related to the duct banks.


For the duct bank diameter and thickness, we have

- $id_{duct}$: duct bank inside diameter

- $od_{duct}$: duct bank outside diameter 

- $t_{duct}$:  duct bank wall thickness

The layout of the duct banks are:

- $row$: The number of rows of duct banks in the layout.

- $col$: The number of columns of duct banks in the layout.

- $d_{vert}$: The vertical distance between the centers of two duct banks.

- $d_{hori}$: The horizontal distance between the centers of two duct banks.

- $d_{top}$: The distance between the center of the __first__ row duct bank and the concrete __top__ surface.

- $d_{down}$: The distance between the center of the __last__ row duct bank and the concrete __button__ surface.

- $d_{left}$: The distance between the center of the __first__ column duct bank and the concrete __left__ surface.

- $d_{right}$: The distance between the center of the __last__ row duct bank and the concrete __right__ surface.

The concrete has the following dimensions:

- $x$: horizontal length

- $y$: vertical height 


The calculation of $R_{ii}$ includes three parts:

- $R_i$: Thermal resistance of the cable and its insulation

- $R_{sd}$: Thermal resistance bewteen cable surface and surrounding duct (including the duct wall)

- $R_c$: Thermal resistance between the duct surface and the surrounding concrete surface

namely, $$ R_{ii} = R_i + R_{sd} + R_c .$$

The detailed calculation of $R_i$ and $R_{sd}$ are given in verification code. Here we assume

- $R_i$ = 0.9 # thermal ohm-foot

- $R_{sd}$ = 1.74 3 thermal ohm-foot

$R_c$ can be approximated by using the distance from the duct bank surface to the nearest concrete surface (we assume the concrete surface has the same temperature). 

Assuming this distance is $d_1$ for cable 1, then we have

$R_c$ = $d_1 \times \rho_{concrete}$,

where $\rho_{concrete}$ is the thermal resistance of the concrete. For illustation, we assume $\rho_{concrete} = 1$.


Before, we mentioned that the thermal heat equilibrium between the duct bank 1 and the concrete is given as

$$T_1 - T_d = Q_1 R_{11} + Q_2 R_{12} + Q_3 R_{13} + Q_4 R_{14},$$

which can also be written as 

$$T_1 - T_d = (Q_1 + \gamma_{12} Q_2 + \gamma_{13} Q_3 + \gamma_{14} Q_4) R_{11} .$$

This assumes that the heat source $Q_2$ is discounted by $\gamma_{12}$ when it reaches to duct bank 1. Similarly, the other two heat sources will also be discounted by $\gamma_{13}$ and $\gamma_{14}$. This is feasible becuase, similar to the electric system, the thermal heat system also follows the superposition principle.

The discount rate $\gamma_{ij}$ (* may need to find the proper term) is determined by the distance between the centers of two duct banks $i$ and $j$. For illustration, we choose

$$ \gamma_{ij} = 1/d_{ij},$$

where $d_{ij}$ is the distance between the two duct bank centers.

Given the horizontal and vertical distances between two neighbor duct bank centers, $d_{ij}$ can be easily calculated. 

The code for calculating $R_{ij}$ is given as follows:

In [50]:
import numpy as np

# Given inputs
id_duct = 5 # inside diameter of the duct/conduit
t_duct  = 0.25 # thickness of the duct 
od_duct = id_duct+2*t_duct # outside diameter of the duct
rd_duct = od_duct/2

d_top = 5.75
d_button = 5.75
d_left  = 5.75
d_right = 5.75

d_hori = 7    # horizontal distance, inch
d_vert = 5.5  # vertical distance, inch
m = 3         # rows of duct banks
n = 2         # columns of duct banks

# Calculate R_ii for each duct bank
R_i = 0.9 # thermal ohm-foot
R_sd = 1.743 # thermal ohm-foot
rho_concrete = 1 # thermal ohm-inch

# Calculate R_ii for each duct bank
R_ii = []
for i in range(m*n):
    # Calculate R_c
    if i < n:  # first row duct banks
        d_1 = d_top - rd_duct
    elif i >= m*n - n:  # last row duct banks
        d_1 = d_button - rd_duct
    elif i % n == 0:  # first column duct banks (excluding first and last rows)
        d_1 = d_left - rd_duct
    elif (i + 1) % n == 0:  # last column duct banks (excluding first and last rows)
        d_1 = d_right - rd_duct
    else:  # inner duct banks
        print('i = ' + str(i))
        # determine how inner it is
        i_row = i // n
        i_col = i % n
        print(i_row, i_col)
        # calculate the distances to the nearest concrete surface in each direction
        d_top_inner = d_top + i_row * d_vert
        d_bottom_inner = d_button + (m - 1 - i_row) * d_vert
        d_left_inner = d_left + i_col * d_hori
        d_right_inner = d_right + (n - 1 - i_col) * d_hori
        # check the results
        print(i_row, m - 1 - i_row, i_col, n - 1 - i_col)
        # find the minimum distance among the four directions
        d_1 = min(d_top_inner, d_bottom_inner, d_left_inner, d_right_inner)
    R_c = d_1 * rho_concrete # thermal ohm-inch/W
    
    # Calculate R_ii
    R_ii.append(R_i + R_sd + R_c)

# Calculate R_ij for each pair of duct banks
R_ij = np.zeros((m*n, m*n))
for i in range(m*n):  # start from zero
    for j in range(m*n):
        if i == j:
            R_ij[i, j] = R_ii[i]
        else:
            i_row = i // n
            i_col = i % n
            j_row = j // n
            j_col = j % n
            row_diff = np.abs(i_row - j_row)
            col_diff = np.abs(i_col - j_col)
            if i_row == j_row:  # same row, horizontal distance
                d_ij = d_hori*col_diff
            elif (i % n) == (j % n):  # same column, vertical distance
                d_ij = d_vert*row_diff
            else:  # diagonal
                d_ij = np.sqrt((d_hori*col_diff)**2 + (d_vert*row_diff)**2)
            gamma_ij = 1/d_ij
            R_ij[i, j] = gamma_ij*R_ii[i]
print(R_ij)

[[5.643      0.80614286 1.026      0.63388491 0.513      0.43279834]
 [0.80614286 5.643      0.63388491 1.026      0.43279834 0.513     ]
 [1.026      0.63388491 5.643      0.80614286 1.026      0.63388491]
 [0.63388491 1.026      0.80614286 5.643      0.63388491 1.026     ]
 [0.513      0.43279834 1.026      0.63388491 5.643      0.80614286]
 [0.43279834 0.513      0.63388491 1.026      0.80614286 5.643     ]]
