# This notebook is used to calculate the simplified duct bank model based on matrix formulation.

## 1. First we show an example of 3x2 duct bank and define several key parameters of the duct bank.

![Example Box 3x2](box3x2.png "Example Box 3x2")

There are several parameters related to the duct banks.


For the duct bank diameter and thickness, we have

- $id_{duct}$: duct bank inside diameter

- $od_{duct}$: duct bank outside diameter 

- $t_{duct}$:  duct bank wall thickness

- $r_d = od_{duct}/2$: radius of the duct bank or channel

The layout of the duct banks are:

- $row$: The number of rows of duct banks in the layout.

- $col$: The number of columns of duct banks in the layout.

- $d_g$: The depth of the concrete top surface below the earth's surface, measured in inches.

- $d_{vert}$: The vertical distance between the centers of two duct banks.

- $d_{hori}$: The horizontal distance between the centers of two duct banks.

- $d_{top}$: The distance between the center of the __first__ row duct bank and the concrete __top__ surface.

- $d_{down}$: The distance between the center of the __last__ row duct bank and the concrete __button__ surface.

- $d_{left}$: The distance between the center of the __first__ column duct bank and the concrete __left__ surface.

- $d_{right}$: The distance between the center of the __last__ row duct bank and the concrete __right__ surface.

The concrete has the following dimensions:

- $x$: horizontal length

- $y$: vertical height 


## 2. Now we show the matrix formulation for 2 by 2 duct bank. 

Suppose we have a 2x2 duct bank system. There are four ducts indexed as $1, 2, 3, 4$. 

- $T_i, \; i=$ 1, 2, 3, 4 is the cable core temperature for cable $i$
- $Q_i$ is the heat source input from cable $i$ in watt

The four ducts are confined in a concrete and buried underground. The heat come from the four cables and finally the concrete reaches a heat equilibrium by dissipating heat to the ambient air via the earth fill on top. We have

- $T_d$ is the duct bank surface temperature in degree Celsius
- $T_a$ is the ambient air temperature in degree Celsius.


First, we define 

- $U_g$: the conductance between the duct bank concrete and the ground.

Now, we define the conductance on the left, top, right, and down of an channel $i$ as follows:

- $U_{il}$: the thermal conductance between the channel $i$ and the object on its __left__ (the object can be the duct bank surface or another channel);

- $U_{it}$: the thermal conductance between the channel $i$ and the object on its __top__ (the object can be the duct bank surface or another channel);

- $U_{ir}$: the thermal conductance between the channel $i$ and the object on its __right__ (the object can be the duct bank surface or another channel);

- $U_{id}$: the thermal conductance between the channel $i$ and the object on its __down__ (the object can be the duct bank surface or another channel).

The specific calculation of the above conductance will be given later. 

In addition, we define the total conductance around channel $i$ as follows:

- $U_{iT}$: the total thermal condutance around the channel $i$, i.e., the summation of conductance from its left, top, right, and down.

This means:

$$U_{iT} = U_{il} + U_{it} + U_{ir} + U_{id}.$$

For the 2 by 2 duct bank, we can write the following 5 thermal equilibrium equations:

\begin{equation}
\begin{aligned}
(T_d - T_a) U_g = Q_1 + Q_2 + Q_3 + Q_4 \\
(T_1 - T_d) U_{1l} + (T_1 - T_d) U_{1t} + (T_1 - T_2) U_{1r} + (T_1 - T_3) U_{1d} = Q_1 \\
(T_2 - T_1) U_{2l} + (T_2 - T_d) U_{2t} + (T_2 - T_d) U_{2r} + (T_2 - T_4) U_{2d} = Q_2 \\
(T_3 - T_d) U_{3l} + (T_3 - T_1) U_{3t} + (T_3 - T_4) U_{3r} + (T_3 - T_d) U_{3d} = Q_3 \\
(T_4 - T_3) U_{4l} + (T_4 - T_2) U_{4t} + (T_4 - T_d) U_{4r} + (T_4 - T_d) U_{4d} = Q_4 \\
\end{aligned}
\end{equation}

Defining

\begin{equation}
\boldsymbol{x} = 
\begin{bmatrix}
T_1 \\
T_2 \\
T_3 \\
T_4 \\
T_d \\
\end{bmatrix}
, \quad
\boldsymbol{u} = 
\begin{bmatrix}
Q_1 \\
Q_2 \\
Q_3 \\
Q_4 \\
T_a \\
\end{bmatrix}
,
\end{equation}

then we have the state-spacee equation as follows:

$$
\boldsymbol{\dot x} = \boldsymbol{A} \boldsymbol{x} + \boldsymbol{B} \boldsymbol{u}
$$

where 

\begin{equation}
\boldsymbol{A} = 
\begin{bmatrix}
0& 0& 0& 0& -U_g \\
-U_{1T}& U_{1r}& U_{1d}& 0& U_{1l}+U_{1t} \\
U_{2l}& -U_{2T}& 0& U_{2d}& U_{2t}+U_{2r} \\
U_{3t}& 0& -U_{3T}& U_{3r}& U_{3l}+U_{3d} \\
0& U_{4t}& U_{4l}& -U_{4T}& U_{4r}+U_{4d} \\
\end{bmatrix}
, \quad
\boldsymbol{B} = 
\begin{bmatrix}
1& 1& 1& 1& U_g\\
1& 0& 0& 0& 0\\
0& 1& 0& 0& 0\\
0& 0& 1& 0& 0\\
0& 0& 0& 1& 0\\
\end{bmatrix}
\end{equation}

When the duct banks, concrete, and earth reach a heat equilibrium, we have $\boldsymbol{\dot x} = 0$.

Therefore, we have 

$$\boldsymbol{A} \boldsymbol{x} + \boldsymbol{B} \boldsymbol{u} = 0,$$

which enables us to get 

$$\boldsymbol{x} = - \boldsymbol{A}^{-1} \boldsymbol{B} \boldsymbol{u} $$


## 3. The matrix formulation for N duct bank (m by n)

Similarly, we can formulate the thermal equilibrium equations as follows:

\begin{equation}
\begin{aligned}
(T_d - T_a) U_g = \sum\limits_{i=1}^{N}Q_i \\
\sum\limits_{k=l,t,r,d} (T_i - T_{ik}) U_{ik} = Q_i, \forall i =1, 2, \cdots, N \\
\end{aligned}
\end{equation}

where 

- $T_{ik}$: the temperature of channel $i$'s $k$ direction ($k = l, t, r, d$ means the direction can be left, top, right, and down) object. When the object is the duct bank surface, then $T_{ik}$ is $T_d$. In other cases, it would be the corresponding channel cable temperature

- $U_{ik}$: the thermal conductance between the channel $i$ and the object on its $k$ direction

The system state $\boldsymbol{x}$ and the system input $\boldsymbol{u}$ are

\begin{equation}
\boldsymbol{x} =
\begin{bmatrix}
T_1 \\
T_2 \\
\vdots \\
T_N \\
T_d \\
\end{bmatrix}
, \quad
\boldsymbol{u} =
\begin{bmatrix}
Q_1 \\
Q_2 \\
\vdots \\
Q_N \\
T_a \\
\end{bmatrix}
.
\end{equation}


then we have the state-spacee equation as follows:
$$
\boldsymbol{\dot x} = \boldsymbol{A} \boldsymbol{x} + \boldsymbol{B} \boldsymbol{u}
$$

where 

\begin{equation}
\boldsymbol{B} =
\begin{bmatrix}
1& 1& \cdots& 1& U_g\\
1& 0& \cdots& 0& 0\\
0& 1& \cdots& 0& 0\\
\vdots& \vdots& \ddots & \vdots& \vdots\\
0& 0& \cdots& 1& 0\\
\end{bmatrix}
\end{equation}

It is worth noting that we do not have an analytic expression for matrix $\boldsymbol{A}$ as its values depends on rows and columns of the duct banks.

We know some values of $\boldsymbol{A}$:

\begin{equation}
\boldsymbol{A} =
\begin{bmatrix}
0& 0& \cdots& 0& -U_g\\
-U_{1T}& ?& \cdots& ?& ?\\
?& -U_{2T}& \cdots& ?& ?\\
\vdots& \vdots& \ddots & \vdots& \vdots\\
?& ?& \cdots& -U_{NT}& ?\\
\end{bmatrix}
\end{equation}


For the values in the other rows, we need to investigate the row and column of channel $i$ and then assign the corresponding values.

- We define a matrix $A_{block}$, which is a N by N matrix. $A_{block}$ matrix is part of $\boldsymbol{A}$ matrix, from the second to last row, and first column to (N-1) column.

- For a row in $A_{block}$, for the diagnal value, it is the negative of the sum of the conductances to its four neighbors. 

- Define another vector $A_{Td}$, it is a N by 1 vector that will be the last column, row 2 to row N of $\boldsymbol{A}$. 

- For the off-diagonal element $A_{block, ij}$, we will check the neighbors of $i$. If the neighbor $k$ is the concrete wall, then add $U_{ik}$ to $A_{Td}$'s $i$th value. If the neighbor $k$ is another channel, then use $U_{ik}$ as the element $A_{block, ij}$, where $j$ is the index of the $i$'s $k$ direction neighbor. 


## 4. Calculating matrix $\boldsymbol{B}$

There is only one variable in matrix $\boldsymbol{B}$, i.e., $U_g$.

### Calculating $U_g$, in W/°C·ft

Define

- $U_g$: in W/°C·ft, is thermal __conductance__ between the duct bank top surface and the ground surface
- $R_g$: in °C·ft/W, is thermal __resistance__ between the duct bank top surface and the ground surface

then we have 
$$ U_g = \frac{1}{R_g}. $$

The thermal resistance between the duct bank top surface and the ground surface can be calculated as:

$$ R_g = 0.012 \rho_{earth} log \frac{(d_g+r_b)}{r_b} $$

where

- $\rho_{earth}$: the thermal conductivity of the ground material, in °C·cm/W

- $d_g$: the depth from the duct bank top surface to the ground surface, in inches

- $r_b$: the radius of the equivalent circle for the duct bank concrete, in inches

$R_g$ is in °C·ft/W, which is also called thermal ohm-foot (used in the United States). Essentially, $R_g$ and $\rho_{earth}$ have the same unit except that the latter use cm instead of ft.

The coefficient 0.012 comes from the standard calculation of the insulation and the unit conversion. A reference for the thermal resistance calculation of the insulation can be found [here](https://www.omnicalculator.com/physics/thermal-resistance). 

The specific derivation of the thermal resistance of a cylinder is shown [here](https://www.studysmarter.us/textbooks/physics/university-physics-with-modern-physics-14th-edition/thermodynamics/q115cp-a-hollow-cylinder-has-length-l-inner-radius-a-and-out/).

In [80]:
# calculate the Ug
import numpy as np

x = 18.5
y = 22.5
dg = 36

# thermal resistance: degree-cm/W
rho_insulation = 550  # insulation
rho_jacket = 550      # insulation jacket
rho_duct = 480        # fiber duct
rho_earth = 120       # earth
rho_concrete = 85     # concrete

def cal_rb(x, y):
    rb_c1 = x/y/2*(4/np.pi-x/y)
    rb_c2 = np.log10(1+y**2/x**2)
    rb_c3 = np.log10(x/2)   
    rb = 10**(rb_c1*rb_c2+rb_c3)

    return rb

rb = cal_rb(x, y)

Rg = 0.012*rho_earth*np.log10(dg+rb/rb) # thermal ohm-foot

Ug = round(1/Rg, 3)

print('The thermal conductance of the earth is: ' + str(Ug) + ' (W/°C·ft)')

The thermal conductance of the earth is: 0.443 (W/°C·ft)


Given $U_g$, then we have matrix $\boldsymbol{B}$ as follows:
\begin{equation}
\boldsymbol{B} =
\begin{bmatrix}
1& 1& \cdots& 1& U_g\\
1& 0& \cdots& 0& 0\\
0& 1& \cdots& 0& 0\\
\vdots& \vdots& \ddots & \vdots& \vdots\\
0& 0& \cdots& 1& 0\\
\end{bmatrix}
\end{equation}

## 5. Calculating matrix $\boldsymbol{A}$

The matrix $\boldsymbol{A}$ comes from the following thermal equilibrium equations:

\begin{equation}
\begin{aligned}
(T_d - T_a) U_g = \sum\limits_{i=1}^{N}Q_i \\
\sum\limits_{k=l,t,r,d} (T_i - T_{ik}) U_{ik} = Q_i, \forall i =1, 2, \cdots, N \\
\end{aligned}
\end{equation}

where 

- $T_{ik}$: the temperature of channel $i$'s $k$ direction ($k = l, t, r, d$ means the direction can be left, top, right, and down) object. When the object is the duct bank surface, then $T_{ik}$ is $T_d$. In other cases, it would be the corresponding channel cable temperature

- $U_{ik}$: the thermal conductance between the channel $i$ and the object on its $k$ direction

### 5.1 Calculating $U_{ik}$ for a given $i$, $k$

Similarly, we start with calculating the thermal resistance and then obtain the thermal conductance.

The calculation of $R_{ik}$ includes three parts:

- $R_{in}$: Thermal resistance of the cable and its insulation

- $R_{sd}$: Thermal resistance bewteen cable surface and surrounding duct (including the duct wall)

- $R_{dk}$: Thermal resistance between the duct surface and the $k$ direction object.

namely, $$ R_{ik} = R_{in} + R_{sd} + R_{dk} .$$

The $R_{in}$ and $R_{sd}$ can be calculated in a similar way like the cylinder. Here we take them as direct inputs as

- $R_{in}$ = 0.9 # thermal ohm-foot, or ˚C·ft/W

- $R_{sd}$ = 1.74 # thermal ohm-foot

$R_{dk}$ can be approximated by using the distance from the duct bank surface to object surface (if the object is another channel, we assume the distance to the center of the other duct bank).

Specifically, we have
$$ R_{dk} = 0.012 \rho_{concrete} log \frac{d_{ik}}{r_d} $$

- $\rho_{concrete}$: the thermal conductivity of the concrete fill, in °C·cm/W

- $d_{ik}$: the distance from the duct bank $i$ center to the $k$ direction object (concrete surface, channel center) , in inches

- $r_d$: the radius of the duct bank, including the duct wall, in inches

Therefore, we can get the $U_{ik}$ as

$$ U_{ik} = \frac{1}{0.25*(R_{in} + R_{sd} + 0.012 \rho_{concrete} log \frac{d_{ik}}{r_d})}. $$

where 0.25 is used to show that we only consider one direction of the cylinder.


### 5.2 Calculating $U_{ik}$, for all $i$, $k$

We have the following input parameters:

- $d_{top}$: The distance between the center of the __first__ row duct bank and the concrete __top__ surface.

- $d_{down}$: The distance between the center of the __last__ row duct bank and the concrete __button__ surface.

- $d_{left}$: The distance between the center of the __first__ column duct bank and the concrete __left__ surface.

- $d_{right}$: The distance between the center of the __last__ row duct bank and the concrete __right__ surface.

For each specific channel $i$, we define a vector $d_{i,vec}$ that stores distances to the four directions (left, top, right, and down), i.e., 

$$d_{i,vec} = [d_{il}, d_{it}, d_{ir}, d_{id}]$$

where 

- $d_{il}$: the distance from the center of channel $i$ to __left__ object

- $d_{it}$: the distance from the center of channel $i$ to __top__ object

- $d_{ir}$: the distance from the center of channel $i$ to __right__ object

- $d_{id}$: the distance from the center of channel $i$ to __down__ object

It is worth noting that the object could be the concrete surface or another channel, which depends on the location of the channel $i$ in the concrete.


For each specific channel $i$, we define another vector $U_{i,vec}$ that stores the conductance to the four directions (left, top, right, and down), i.e., 

$$U_{i,vec} = [U_{il}, U_{it}, U_{ir}, U_{id}]$$

where 

- $U_{il}$: the thermal conductance from the center of channel $i$ to __left__ object

- $U_{it}$: the thermal conductance from the center of channel $i$ to __top__ object

- $U_{ir}$: the thermal conductance from the center of channel $i$ to __right__ object

- $U_{id}$: the thermal conductance from the center of channel $i$ to __down__ object

The calculation of $U_{i,vec}$ depends on the values of $d_{i,vec}$.


### Algorithm to calculate $d_{i,vec}$ and $U_{i,vec}$

For m by n duct bank , we count it by looping the rows. This means, the first row, it would be channel $1, 2, \cdots, n$, where $n$ is the number of columns. 

For channel $i$, we can first find its row and column as $i_{row}$ and $i_{col}$. 

We define 

$$i_{loc} = (i_{row}, i_{col}).$$

Define $k = [0, 1, 2, 3]$ to represent the four directions

- $k = 0$: left

- $k = 1$: top

- $k = 2$: right

- $k = 3$: down

To loop these four direction, we can define 

$$k_{pair} = [(0, -1), (-1, 0), (0, 1), (1, 0)]. $$

Then, we have the channel $i$'s neighbor set as

$$i_{nbor} = i_{loc} + k_{pair}$$.

For the specific $k$ direction neighbor, we have the location as

$$k_{loc} = i_{loc} + k_{pair}[k] = (i_{row}, i_{col}) + k_{pair}[k] .$$

and

$$k_{loc} = (k_{loc, row}, k_{loc, col})$$


It is worth noting that the object could be the concrete surface or another channel, which depends on the location of the channel $i$ in the concrete.

Loop the channel $i$'s neighbor $k$, we have the following 4 cases

- 1. left neighbor: $k = 0$, $k_{loc} = i_{loc} + k_{pair}[0] = (i_{row}, i_{col}) + (0, -1)$

check if $k_{loc, col}$ < 0 or not. 

If yes to $k_{loc, col} < 0$, then the left object is the concrete wall, we have $d_{il} = d_{left}$

If no to $k_{loc, col} < 0$, then the left object is another channel, we have $d_{il} = d_{hori}$


- 2. top neighbor: $k = 1$, $k_{loc} = i_{loc} + k_{pair}[1] = (i_{row}, i_{col}) + (-1, 0)$

check if $k_{loc, row}$ < 0 or not. 

If yes to $k_{loc, row}$ < 0, then the top object is the concrete wall, we have $d_{it} = d_{top}$

If no to $k_{loc, row}$ < 0, then the top object is another channel, we have $d_{it} = d_{vert}$

- 3. right neighbor, $k = 2$, $k_{loc} = i_{loc} + k_{pair}[2] = (i_{row}, i_{col}) + (0, 1)$

check if $k_{loc, col}$ > (n-1) or not. 

If yes to $k_{loc, col}$ > (n-1), then the right object is the concrete wall, we have $d_{ir} = d_{right}$

If no to $k_{loc, col}$ > (n-1), then the right object is another channel, we have $d_{ir} = d_{hori}$


- 4. down neighbor, $k = 3$, $k_{loc} = i_{loc} + k_{pair}[3] = (i_{row}, i_{col}) + (1, 0)$

check if $k_{loc, row}$ > (m-1)$ or not. 

If yes to $k_{loc, row}$ > (m-1), then the down object is the concrete wall, we have $d_{id} = d_{down}$

If no to $k_{loc, row}$ > (m-1), then the down object is another channel, we have $d_{id} = d_{vert}$



### Part 1. Code to calculate $U_g$, $U_{vec}$

In [1]:
import numpy as np

# Given inputs
id_duct = 5 # inside diameter of the duct/conduit
t_duct  = 0.25 # thickness of the duct 
od_duct = id_duct+2*t_duct # outside diameter of the duct
r_d = od_duct/2

d_top = 5.75
d_down = 5.75
d_left  = 5.75
d_right = 5.75

d_hori = 7    # horizontal distance, inch
d_vert = 5.5  # vertical distance, inch
m = 3         # rows of duct banks
n = 2         # columns of duct banks
N = m*n

# given thermal resistance
R_i = 0.9 # thermal ohm-foot, or ˚C·ft/W
R_sd = 1.74 # thermal ohm-foot

# thermal resistance: degree-cm/W
rho_insulation = 550  # insulation
rho_jacket = 550      # insulation jacket
rho_duct = 480        # fiber duct
rho_earth = 120       # earth
rho_concrete = 85     # concrete

x = 18.5        # concrete horizontal width
y = 22.5        # concrete vertical depth
dg = 36      # distance from the ground to the concrete top surface

# 1. Calculate Ug
# function in calculating the equivalent circle radius
def cal_rb(x, y):
    rb_c1 = x/y/2*(4/np.pi-x/y)
    rb_c2 = np.log10(1+y**2/x**2)
    rb_c3 = np.log10(x/2)   
    rb = 10**(rb_c1*rb_c2+rb_c3)
    return rb

rb = cal_rb(x, y)
Rg = 0.012*rho_earth*np.log10(dg+rb/rb) # thermal ohm-foot
Ug = 1/Rg
print('The thermal conductance of the earth (U_g) (W/°C·ft): \n' + str(round(Ug, 4)))

# 2. calculate U_vec

# Initialize an array to store the distances and conductances for each channel
d_vec = np.zeros((N, 4))
U_vec = np.zeros((N, 4))

k_pair = [(0, -1), (-1, 0), (0, 1), (1, 0)]

# Loop through each channel
for i in range(N):
    # Find the row and column of the current channel
    i_row = i // n
    i_col = i % n
    
    # Initialize arrays to store the distances and conductances to the neighbors
    nbor_d_vec = np.zeros(4)
    nbor_U_vec = np.zeros(4)
    
    # Loop through each of the four directions
    for k in range(4):
        # Find the location of the neighbor in the k direction
        k_loc = (i_row + k_pair[k][0], i_col + k_pair[k][1])
        k_loc_row, k_loc_col = k_loc
        
        # Calculate the distance to the neighbor (either another channel or the concrete)
        if k == 0:
            # left neighbor
            if k_loc_col < 0:
                nbor_d_vec[k] = d_left
            else:
                nbor_d_vec[k] = d_hori
        elif k == 1:
            # top neighbor
            if k_loc_row < 0:
                nbor_d_vec[k] = d_top
            else:
                nbor_d_vec[k] = d_vert
        elif k == 2:
            # right neighbor
            if k_loc_col > (n-1):
                nbor_d_vec[k] = d_right
            else:
                nbor_d_vec[k] = d_hori
        else:
            # down neighbor
            if k_loc_row > (m-1):
                nbor_d_vec[k] = d_down
            else:
                nbor_d_vec[k] = d_vert
            
                
        # Calculate the thermal conductance to the neighbor
        d_ik = nbor_d_vec[k]
        R_ik = 0.25 * (R_i + R_sd + 0.012 * rho_concrete * np.log(d_ik/r_d))
        U_ik = 1/R_ik
        
        # Store the conductance to the current channel's neighbors
        nbor_U_vec[k] = U_ik
    
    # Store the distances and conductances to the current channel's neighbors
    d_vec[i] = nbor_d_vec
    U_vec[i] = nbor_U_vec

U_vec = np.round(U_vec, 4)
print('The distance to four neighbors are (inches): \n' + str(d_vec))
print('The conductance to four neighbhors are (W/°C·ft): \n' + str(U_vec))

The thermal conductance of the earth (U_g) (W/°C·ft): 
0.4428
The distance to four neighbors are (inches): 
[[5.75 5.75 7.   5.5 ]
 [7.   5.75 5.75 5.5 ]
 [5.75 5.5  7.   5.5 ]
 [7.   5.5  5.75 5.5 ]
 [5.75 5.5  7.   5.75]
 [7.   5.5  5.75 5.75]]
The conductance to four neighbhors are (W/°C·ft): 
[[1.1791 1.1791 1.1133 1.1951]
 [1.1133 1.1791 1.1791 1.1951]
 [1.1791 1.1951 1.1133 1.1951]
 [1.1133 1.1951 1.1791 1.1951]
 [1.1791 1.1951 1.1133 1.1791]
 [1.1133 1.1951 1.1791 1.1791]]


### Part 2. Code to calculate the A matrix and B matrix

In [2]:
# Calculate A_block
A_block = np.zeros((N, N))
A_Td = np.zeros(N)

# Loop through each channel
for i in range(N):
    # Find the row and column of the current channel
    i_row = i // n
    i_col = i % n
    
    # Initialize variable to store sum of conductances to neighbors
    sum_U = 0
    
    # Loop through each of the four directions
    for k in range(4):
        # Find the location of the neighbor in the k direction
        k_loc = (i_row + k_pair[k][0], i_col + k_pair[k][1])
        k_loc_row, k_loc_col = k_loc
        
        # Add the conductance to the neighbor to the sum_U variable
        sum_U += U_vec[i, k]
        
        # Check if neighbor is within duct bank
        if k_loc_row >= 0 and k_loc_row < m and k_loc_col >= 0 and k_loc_col < n:
            # Calculate the index of the neighbor in the channel array
            k_idx = k_loc_row * n + k_loc_col
            
            # Assign the conductance to the neighbor to the corresponding position in A_block
            A_block[i, k_idx] = U_vec[i, k]
            
        # If neighbor is outside duct bank, assume it is the concrete wall
        else:
            # Add the conductance to the concrete to the A_Td variable
            A_Td[i] += U_vec[i, k]
    
    # Assign the sum of conductances to neighbors to the diagonal of A_block
    A_block[i, i] = -sum_U

# Combine A_block and A_Td into A matrix
A = np.zeros((N+1, N+1))
A[1:, :-1] = A_block
A[1:, -1] = A_Td
A[0, -1] = -Ug
A = np.round(A, 3)
print('The four neighbor conductance of each channel (W/°C·ft): \n' + str(np.round(U_vec, 3)))
row_sum = np.sum(U_vec, axis=1)
print('The total conductance of each channel (W/°C·ft): \n' + str(row_sum))
print('A matrix is: \n' + str(A))
A_inv = np.linalg.inv(A)
A_inv = np.round(A_inv, 3)
print('A inverse is: \n' + str(A_inv))

The four neighbor conductance of each channel (W/°C·ft): 
[[1.179 1.179 1.113 1.195]
 [1.113 1.179 1.179 1.195]
 [1.179 1.195 1.113 1.195]
 [1.113 1.195 1.179 1.195]
 [1.179 1.195 1.113 1.179]
 [1.113 1.195 1.179 1.179]]
The total conductance of each channel (W/°C·ft): 
[4.6666 4.6666 4.6826 4.6826 4.6666 4.6666]
A matrix is: 
[[ 0.     0.     0.     0.     0.     0.    -0.443]
 [-4.667  1.113  1.195  0.     0.     0.     2.358]
 [ 1.113 -4.667  0.     1.195  0.     0.     2.358]
 [ 1.195  0.    -4.683  1.113  1.195  0.     1.179]
 [ 0.     1.195  1.113 -4.683  0.     1.195  1.179]
 [ 0.     0.     1.195  0.    -4.667  1.113  2.358]
 [ 0.     0.     0.     1.195  1.113 -4.667  2.358]]
A inverse is: 
[[-2.256 -0.252 -0.071 -0.08  -0.041 -0.024 -0.016]
 [-2.256 -0.071 -0.252 -0.041 -0.08  -0.016 -0.024]
 [-2.256 -0.08  -0.041 -0.275 -0.086 -0.08  -0.041]
 [-2.256 -0.041 -0.08  -0.086 -0.275 -0.041 -0.08 ]
 [-2.256 -0.024 -0.016 -0.08  -0.041 -0.252 -0.071]
 [-2.256 -0.016 -0.024 -0.041 -

In [3]:
# Create B matrix by adding the identity matrix as the block diagonal and Ug as the last column of the first row
B = np.zeros((N+1, N+1))
B[0, :-1] = 1
B[0, -1] = Ug
B[1:, :-1] = np.identity(N)

# Print the resulting matrix B
print('B matrix is: \n' + str(np.round(B, 3)))

B matrix is: 
[[1.    1.    1.    1.    1.    1.    0.443]
 [1.    0.    0.    0.    0.    0.    0.   ]
 [0.    1.    0.    0.    0.    0.    0.   ]
 [0.    0.    1.    0.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.    0.   ]
 [0.    0.    0.    0.    0.    1.    0.   ]]


### Part 3: Calculate the temperature

In [6]:
# define the input u
R_dc = 8.6 # microhoms per foot
I_vec = np.full(N, 0.6) # in kiloampere
Q_vec = np.square(I_vec)*R_dc
print('The input heat vector (in W/ft): \n' + str(Q_vec))   # in W/ft
T_a = 25 # ambient temperature is 25 °C
u = np.append(Q_vec, T_a)
print('The input vector is: \n' + str(u))
# check the results
T_vec = - A_inv @ B @ u
print('The temperature vector is (in °C): \n' + str(np.round(T_vec, 3)))

The input heat vector (in W/ft): 
[3.096 3.096 3.096 3.096 3.096 3.096]
The input vector is: 
[ 3.096  3.096  3.096  3.096  3.096  3.096 25.   ]
The temperature vector is (in °C): 
[68.381 68.381 68.75  68.75  68.381 68.381 66.913]
